---
# tasks file for ansible-role-cultivator:credential_type.yml

#
# -----------------------------------------------------------------------------
# Credential Type Tasks
# -----------------------------------------------------------------------------
#
#

# Create Custom Credential Types
- name: Create a credential type
  tower_credential_type:
    name: "{{ item.1.name }}"
    state: present
    description: "{{ item.1.description | default(omit) }}"
    kind: "cloud"
    inputs: "{{ item.1.inputs }}"
    injectors: "{{ item.1.injectors }}"
    tower_host: "{{ cultivator_tower_server }}"
    tower_username: "{{ cultivator_tower_username }}"
    tower_password: "{{ cultivator_tower_password }}"
    validate_certs: "{{ cultivator_tower_validate_certs }}"
  loop: "{{ cultivator_tower_objects.organisations | subelements('credential_types') }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
  vars:
    ansible_python_interpreter: '{{ cultivator_virtualenv_path }}/bin/python'
