---
# tasks file for ansible-role-cultivator:credential.yml

#
# -----------------------------------------------------------------------------
# Credential Tasks
# -----------------------------------------------------------------------------
#
#

# Create a Credential

- name: Create a  credential (tower module)
  tower_credential:
    name: "{{ item.1.name }}"
    description: "{{ item.1.description | default(omit) }}"
    organization: "{{ item.0.name }}"
    state: present
    kind: "{{ item.1.kind }}"
    host: "{{ item.1.host | default(omit) }}"
    username: "{{ item.1.username | default(omit) }}"
    password: "{{ item.1.password | default(omit) }}"
    ssh_key_data: "{{ item.1.ssh_key_data | default(omit) }}"
    tower_host: "{{ cultivator_tower_server }}"
    tower_username: "{{ cultivator_tower_username }}"
    tower_password: "{{ cultivator_tower_password }}"
    validate_certs: "{{ cultivator_tower_validate_certs }}"
  when: item.1.inputs is undefined
  loop: "{{ cultivator_tower_objects.organisations | subelements('credentials') }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
  vars:
    ansible_python_interpreter: '{{ cultivator_virtualenv_path }}/bin/python'

- name: Create a  credential
  command: >-
    tower-cli credential create
    --name "{{ item.1.name }}"
    --description "{{ item.1.description | default('') }}"
    --organization "{{ item.0.name }}"
    --credential-type "{{ item.1.kind }}"
    --inputs "{{ item.1.inputs }}"
    --tower-host "{{ cultivator_tower_server }}"
    --tower-username "{{ cultivator_tower_username }}"
    --tower-password "{{ cultivator_tower_password }}"
    {{ cultivator_tower_validate_certs | ternary(omit, '--insecure', omit) }}
  when: item.1.inputs is defined
  loop: "{{ cultivator_tower_objects.organisations | subelements('credential') }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
  vars:
    ansible_python_interpreter: '{{ cultivator_virtualenv_path }}/bin/python'
