---
# tasks file for ansible-role-cultivator:job_templates.yml

#
# -----------------------------------------------------------------------------
# Job Template Tasks
# -----------------------------------------------------------------------------
#
#

# Create Job Temnplates
- name: "[Cultivator - Job Templates] Create Job Templates"
  tower_job_template:
    name: "{{ item.1.name }}"
    job_type: "{{ item.1.job_type }}"
    playbook: "{{ item.1.playbook }}"
    project: "{{ item.1.project }}"
    inventory: "{{ item.1.inventory }}"
    state: present
    tower_host: "{{ cultivator_tower_server }}"
    tower_username: "{{ cultivator_tower_username }}"
    tower_password: "{{ cultivator_tower_password }}"
    validate_certs: "{{ cultivator_tower_validate_certs }}"
    credential: "{{ item.1.credential }}"
  loop: "{{ cultivator_tower_objects.organisations | subelements('job_templates') }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
  vars:
    ansible_python_interpreter: '{{ cultivator_virtualenv_path }}/bin/python'
