---
# tasks file for ansible-role-cultivator:job_template_credential.yml

#
# -----------------------------------------------------------------------------
# Job Template/Credential Tasks
# -----------------------------------------------------------------------------
#
#

# Add a credential to a job template
# This is required because you can currently only add a single credential to a job template using the tower_job_template module.
# This code instead addseach credential one by one. They should be defined as a pair such as the example below:

# job_template-credentials:
#   - job_template: "demo"
#     credential: "cred1"
#   - job_template: "demo"
#     credential: "cred2"

- name: "Add extra credentials"
  command: >-
    tower-cli job_template associate_credential
    --job-template "{{ item.1.job_template }}"
    --credential "{{ item.1.credential }}"
    --tower-host "{{ cultivator_tower_server }}"
    --tower-username "{{ cultivator_tower_username }}"
    --tower-password "{{ cultivator_tower_password }}"
    {{ cultivator_tower_validate_certs | ternary(omit, '--insecure', omit) }}
  register: result
  changed_when: false
  loop: "{{ cultivator_tower_objects.organisations | subelements('job_template_credentials') }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
  vars:
    ansible_python_interpreter: '{{ cultivator_virtualenv_path }}/bin/python'
