---
# tasks file for ansible-role-cultivator:orgs.yml

#
# -----------------------------------------------------------------------------
# Orgs Tasks
# -----------------------------------------------------------------------------
# Any Organisation Tasks
#


# Create Orgs
- name: "[Cultivator - Orgs] Create Organisations"
  tower_organization:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
    tower_host: "{{ cultivator_tower_server }}"
    tower_username: "{{ cultivator_tower_username }}"
    tower_password: "{{ cultivator_tower_password }}"
    validate_certs: "{{ cultivator_tower_validate_certs }}"
  loop: "{{ cultivator_tower_orgs }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
  
