---
# tasks file for ansible-role-cultivator:users.yml

#
# -----------------------------------------------------------------------------
# User Tasks
# -----------------------------------------------------------------------------
# Any User Tasks
#

# Create Users
- name: "[Cultivator - Users] Create Users"
  tower_user:
    username: "{{ item.username }}"
    first_name: "{{ item.first_name }}"
    last_name: "{{ item.last_name }}"
    email: "{{ item.email }}"
    password: "{{ item.password }}"
    user_type: "{{ item.user_type }}"
    state: present
    tower_host: "{{ cultivator_tower_server }}"
    tower_username: "{{ cultivator_tower_username }}"
    tower_password: "{{ cultivator_tower_password }}"
    validate_certs: "{{ cultivator_tower_validate_certs }}"
  loop: "{{ cultivator_tower_objects.organisations | dict2items | subelements('users') }}"
  environment:
    PATH: '{{ cultivator_virtualenv_path }}/bin:{{ ansible_env.PATH }}'
    PYTHONPATH: '{{ cultivator_virtualenv_path }}/bin/python'
